server:
  port: 8080

spring:
  application:
    name: meet
  mail:
    host: smtp.gmail.com
    port: 587
    username: your email
    password: Your app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

google:
  oauth:
    client-id: YOUR CLIENT ID
    client-secret: YOUR CLIENT SECRET
#    scope: openid, profile, email, https://www.googleapis.com/auth/calendar.events
    redirect-uri : http://localhost:8080/api/master/google-meet/callback
    token-url: https://oauth2.googleapis.com/token
    scopes:
      - https://www.googleapis.com/auth/meetings.space.created
      - https://www.googleapis.com/auth/meetings
      - https://www.googleapis.com/auth/calendar
      - https://www.googleapis.com/auth/userinfo.email
      - openid
      - profile
      - email
      - https://www.googleapis.com/auth/calendar.events

