server:
  port: 8080

spring:
  application:
    name: googlemeet
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 803204819664-udgf72ti6vhkrf76sbcqsiq3dgbscsdg.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email, https://www.googleapis.com/auth/calendar.events
        provider:
          google:
            authorization-uri: http://localhost:8080/login/oauth2/code/google
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
