server:
  port: 8080

spring:
  application:
    name: meet

google:
  oauth:
    client-id:
    client-secret:
    redirect-uri : http://localhost:8080/api/master/google-meet/callback
    token-url: https://oauth2.googleapis.com/token
    scopes:
      - https://www.googleapis.com/auth/meetings.space.created
      - https://www.googleapis.com/auth/meetings
      - https://www.googleapis.com/auth/calendar
      - https://www.googleapis.com/auth/userinfo.email
      - openid
      - profile
      - email
      - https://www.googleapis.com/auth/calendar.events

